const { __ } = wp.i18n;
const { select } = wp.data;
const { createHigherOrderComponent } = wp.compose;
const { Fragment } = wp.element;
const { InspectorControls } = wp.blockEditor;
const { TextareaControl, SelectControl, PanelBody, IconButton, FormTokenField } = wp.components;

const withInspectorControls = createHigherOrderComponent((BlockEdit) => {
    return (props) => {

        const { inlineStyle } = props.attributes;
        const isAdmin = select('core').canUser('create', 'users');

        return (
            <>
                <BlockEdit {...props} />
                {isAdmin ?
                    <InspectorControls key="inspector">
                        <PanelBody title={__('Inline styling', 'custom-blocks')} initialOpen={false}>
                            <TextareaControl
                                help={__('Notice: This inline style will override any other inline style generated by Gutenberg.', 'custom-blocks')}
                                value={inlineStyle}
                                onChange={inlineStyle => props.setAttributes({ inlineStyle })}
                            />
                        </PanelBody>
                    </InspectorControls>
                    : ''}
            </>
        );
    };
}, 'withInspectorControl');

wp.hooks.addFilter('editor.BlockEdit', 'custom-blocks/inline-style/inspector', withInspectorControls);
